# https://docs.docker.com/compose/how-tos/multiple-compose-files/include/
include:
  - compose.scorpio.yaml

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  markdownlint:
    image: itkdev/markdownlint
    volumes:
      - .:/md
    profiles:
      - dev
